FROM rust:1.43

RUN apt update &&\ 
    apt upgrade -y

RUN rustup update nightly &&\ 
    rustup default nightly

WORKDIR /usr/src/myapp

COPY Cargo.toml /usr/src/myapp/code/Cargo.toml
COPY Rocket.toml /usr/src/myapp/code/Rocket.toml
COPY src/ /usr/src/myapp/code/src/
COPY templates/ /usr/src/myapp/code/templates/
COPY static/ /usr/src/myapp/code/static/

WORKDIR /usr/src/myapp/code

RUN cargo build

CMD ["cargo", "run", "--manifest-path=/usr/src/myapp/code/Cargo.toml"]