apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mattiarubinicom
  annotations:
    kompose.cmd: kompose convert -o container/kompose/
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: homepage
  name: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: homepage
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o container/kompose/
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: homepage
    spec:
      containers:
        - image: homepage
          name: homepage
          ports:
            - containerPort: 80
          resources: {}
          imagePullPolicy: Never
      restartPolicy: Always
status: {}
