apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kompose/
    kompose.version: 1.24.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mattiarubinicom
  name: mattiarubinicom
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mattiarubinicom
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kompose/
        kompose.version: 1.24.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mattiarubinicom
    spec:
      containers:
        - image: mattiarubinicom
          name: mattiarubinicom
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
