# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.0
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-11-12T14:25:29Z"
  labels:
    app: pod-mattiarubinicom
  name: pod-mattiarubinicom
spec:
  ports:
  - name: "80"
    nodePort: 32283
    port: 80
    protocol: TCP
    targetPort: 0
  selector:
    app: pod-mattiarubinicom
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-12T14:25:29Z"
  labels:
    app: pod-mattiarubinicom
  name: pod-mattiarubinicom
spec:
  containers:
  - image: localhost/pod-mattiarubinicom_mattiarubinicom:latest
    name: mattiarubinicom
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /usr/src/myapp
  dnsConfig: {}
  restartPolicy: Never
status: {}

